version: 2

jobs:
  build:
    docker:
    - image: ankyra/escape:latest

    steps:
    - checkout
    - run: 
        name: Build Escape release
        command: |
          escape run build && escape run test && \
            if [ "$CIRCLE_BRANCH" = "master" ] ; then
              escape run release --skip-build --skip-deploy
            fi
